import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./ThemeProvider";
import { ErrorBoundary } from "react-error-boundary";
import { ErrorFallback } from "@/Components/utility/Error/ErrorFallback";
import { NavbarComponent } from "@/Components/page/Nav&Footer/NavbarComponent";
import { FooterComponent } from "@/Components/page/Nav&Footer/Footer";
import { GlobalErrorAlerts } from "@/Components/utility/Error/GlobalErrorAlerts";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PRVEMY-TOIEC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans antialiased"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary FallbackComponent={ErrorFallback}>
            <NavbarComponent />
            <main className="flex-grow">{children}</main>
          </ErrorBoundary>
          <FooterComponent />
        </ThemeProvider>
        <GlobalErrorAlerts />
      </body>
    </html>
  );
}
