import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils/utils";
import { ThemeProvider } from "./ThemeProvider";
import { ErrorBoundary } from "react-error-boundary";
import { ErrorFallback } from "@/Components/utility/Error/ErrorFallback";
import { GlobalErrorAlerts } from "@/Components/utility/Error/GlobalErrorAlerts";
import { ClientLayoutWrapper } from "@/Components/layout/ClientLayoutWrapper";
import { getUserWithProfile } from "@/lib/auth/getUserProfile";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PRVEMY-TOIEC",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = getUserWithProfile();

  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans antialiased",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary FallbackComponent={ErrorFallback}>
            <ClientLayoutWrapper user={user}>{children}</ClientLayoutWrapper>
          </ErrorBoundary>
        </ThemeProvider>
        <GlobalErrorAlerts />
      </body>
    </html>
  );
}
